### ISSUE TITLE
WE NEED OJ!!!!

### ISSUE THREAD

**Issue by dalaeyelids** [sdufeACM/Review#7]
山财老学长求一个不用VPN能直连的OJ链接
红豆泥阿里嘎多

**Comment by xia0ne** [comment]
学长，非常抱歉，我不只一次尝试在OJ服务器部署FRP给同学们提供外网服务，但是都被学校深信服检测并警告，于是不再提供此类服务，还请学长寻找另外的可以外网访问的OJ，或者找再读的学弟学妹借一个账号使用

例如：
1. [codeforces](https://codeforces.com/problemset)
2. [HDUOJ](https://acm.hdu.edu.cn/)

**Comment by dalaeyelids** [comment]
> 学长，非常抱歉，我不只一次尝试在OJ服务器部署FRP给同学们提供外网服务，但是都被学校深信服检测并警告，于是不再提供此类服务，还请学长寻找另外的可以外网访问的OJ，或者找再读的学弟学妹借一个账号使用
> 
> 例如：
> 
> 1. [codeforces](https://codeforces.com/problemset)
> 2. [HDUOJ](https://acm.hdu.edu.cn/)

哇哦，回复的好迅速hhhh
看了看学院新闻，发现现在都是以编程题进行专业分流考试了，而且有很多编程比赛活动，感觉学院越来越重视实践能力了。
那就祝山财计科越来越好吧

**Comment by dalaeyelids** [comment]
> 学长，非常抱歉，我不只一次尝试在OJ服务器部署FRP给同学们提供外网服务，但是都被学校深信服检测并警告，于是不再提供此类服务，还请学长寻找另外的可以外网访问的OJ，或者找再读的学弟学妹借一个账号使用
> 
> 例如：
> 
> 1. [codeforces](https://codeforces.com/problemset)
> 2. [HDUOJ](https://acm.hdu.edu.cn/)

感谢回复，祝学业有成，生活愉快，enjoy life，genshin impact！！
